kind: pipeline
type: docker
name: Build for development

steps:
  - name: "build app"
    image: golang:1.17
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - echo "DB_HOST=ec2-13-228-152-170.ap-southeast-1.compute.amazonaws.com" > .env
      - echo "DB_PASS='hS1G3bEjpV9H'" >> .env
      - echo "DB_PORT=3306" >> .env
      - echo "DB_USER=kemenag" >> .env
      - echo "DB_NAME=db_kemenag" >> .env
      - echo "DB_DRIVER=mysql" >> .env
      - cat .env
      - go get
      - go build -o main
  - name: "build image"
    image: plugins/docker
    settings:
      repo: primeskills/kemenag-be-chat
      tags:
        - dev-${DRONE_COMMIT_SHA:0:6}
        - dev-latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy development

steps:
  - name: ssh pull image
    image: appleboy/drone-ssh
    environment:
      IMAGE_NAME: primeskills/kemenag-be-chat:dev-${DRONE_COMMIT_SHA:0:6}
      CONTAINER_NAME: chat-service
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: server_username
      key:
        from_secret: rsa_key
      port: 22
      envs:
        - IMAGE_NAME
        - CONTAINER_NAME
      script:
        - echo "Pull image docker"
        - docker pull $IMAGE_NAME
        - docker stop $CONTAINER_NAME
        - docker rm $CONTAINER_NAME
        - docker system prune -a -f
        - echo "Done"
        - docker run -d --name $CONTAINER_NAME --publish 9093:8081 $IMAGE_NAME
        - echo "Done"

trigger:
  branch:
    - master
  event:
    - push
depends_on:
  - Build for development

